### ISSUE TITLE
undefined method `read_mac_addresses' on vagrant up

### ISSUE THREAD

**Issue by ocxo** [WinRb/vagrant-windows#10]
``` bash
[default] Waiting for VM to boot. This can take a few minutes.
WIN-FNO6SSRUL91
[default] VM booted and ready for use!
[default] Configuring and enabling network interfaces...
[default] Forcing shutdown of VM...
[Berkshelf] cleaning Vagrant's shelf
[default] Destroying VM and associated drives...
/Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-windows-0.1.1/lib/vagrant-windows/guest/windows.rb:64:in `configure_networks': undefined method `read_mac_addresses' for #<Vagrant::Driver::VirtualBox_4_2:0x007f95076f54e8> (NoMethodError)
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/network.rb:72:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/clear_network_interfaces.rb:26:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/host_name.rb:10:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/share_folders.rb:20:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/clear_shared_folders.rb:13:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/nfs.rb:41:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/prune_nfs_exports.rb:15:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/provision.rb:27:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:84:in `block in finalize_action'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:84:in `block in finalize_action'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/forward_ports.rb:24:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/check_port_collisions.rb:42:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/env/set.rb:16:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/clear_forwarded_ports.rb:13:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/clean_machine_folder.rb:17:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/check_accessible.rb:18:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/general/validate.rb:13:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/berkshelf-1.0.2/lib/berkshelf/vagrant/action/validate.rb:25:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/general/check_virtualbox.rb:23:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/match_mac_address.rb:16:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/default_name.rb:17:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/check_guest_additions.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/import.rb:31:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/check_box.rb:28:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/vm/check_accessible.rb:18:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/general/validate.rb:13:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/general/check_virtualbox.rb:23:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/builder.rb:92:in `call'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/runner.rb:49:in `block in run'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/action/runner.rb:49:in `run'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/vm.rb:192:in `run_action'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/vm.rb:145:in `up'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/command/up.rb:31:in `block in execute'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/command/base.rb:116:in `block in with_target_vms'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/command/base.rb:111:in `each'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/command/base.rb:111:in `with_target_vms'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/command/up.rb:24:in `execute'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/cli.rb:42:in `execute'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/lib/vagrant/environment.rb:167:in `cli'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/gems/vagrant-1.0.5/bin/vagrant:43:in `<top (required)>'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/bin/vagrant:23:in `load'
    from /Users/Adam/.rbenv/versions/1.9.3-p286/bin/vagrant:23:in `<main>'
```

**Comment by pmorton** [comment]
@fromonesrc It is not clear, but is is highly likely that this is due to https://github.com/BIAINC/vagrant-windows/pull/8. Can you confirm that this resolves this issue. If so, I will publish a new version of this gem.

**Comment by ocxo** [comment]
That seems to have cleared up the read_mac_address problem but now I'm getting this on vagrant up.

``` bash
[default] Waiting for VM to boot. This can take a few minutes.
WIN-FNO6SSRUL91
[default] VM booted and ready for use!
[default] Configuring and enabling network interfaces...

[default] Setting host name...
Invalid Verb Switch.
translation missing: en.vagrant.errors.winrm_bad_exit_status
```

**Comment by pmorton** [comment]
Most of these winrm_bad_exit_status tend to be transport errors with WinRM. Can you confirm that this is still happening?

**Comment by ocxo** [comment]
Sorry to say I forget what the problem was but it wasn't vagrant-windows. Thanks for following up.
