### ISSUE TITLE
When starting vagrant on a windows host, with the puppet provisioner, if the modules path is supplied throws an error 

### ISSUE THREAD

**Issue by tvjames** [WinRb/vagrant-windows#107]
When running running a windows guest (2008R2) on a windows host (Win7) using the puppet modules config: 

```
config.vm.provision :puppet, :options => ["--verbose --environment vagrant"] do |puppet|
  puppet.module_path    = "puppet/modules"
  puppet.manifests_path = "puppet/manifests"
  puppet.manifest_file  = "default.pp"
  puppet.facter = {
    "domain" => "local",
    "kernel" => "windows",
    "operatingsystem" => "windows",
    "osfamily" => "windows"
  }
end
```

Results in the following error, which I can only reproduce on windows, a mac host works fine:

```
C:/Users/tjames/.vagrant.d/gems/gems/vagrant-windows-1.2.1/lib/vagrant-windows/monkey_patches/plugins/provisioners/puppet/provisioner/puppet.rb:67:in `join': can't convert Vagrant::Config::V2::DummyConfig to String (Vagrant::Config::V2::DummyConfig#to_str gives Vagrant::Config::V2::DummyConfig) (TypeError)
            from C:/Users/tjames/.vagrant.d/gems/gems/vagrant-windows-1.2.1/lib/vagrant-windows/monkey_patches/plugins/provisioners/puppet/provisioner/puppet.rb:67:in `block in configure_on_windows'
            from C:/Users/tjames/.vagrant.d/gems/gems/vagrant-windows-1.2.1/lib/vagrant-windows/monkey_patches/plugins/provisioners/puppet/provisioner/puppet.rb:66:in `each'
            from C:/Users/tjames/.vagrant.d/gems/gems/vagrant-windows-1.2.1/lib/vagrant-windows/monkey_patches/plugins/provisioners/puppet/provisioner/puppet.rb:66:in `each_with_index'
            from C:/Users/tjames/.vagrant.d/gems/gems/vagrant-windows-1.2.1/lib/vagrant-windows/monkey_patches/plugins/provisioners/puppet/provisioner/puppet.rb:66:in `configure_on_windows'
            from C:/Users/tjames/.vagrant.d/gems/gems/vagrant-windows-1.2.1/lib/vagrant-windows/monkey_patches/plugins/provisioners/puppet/provisioner/puppet.rb:17:in `block in <class:Puppet>'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/provision.rb:41:in `blockin call'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/provision.rb:40:in `each'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/provision.rb:40:in `call'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `block in run'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in `busy'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `run'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/call.rb:51:in `call'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `block in run'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in `busy'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `run'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/call.rb:51:in `call'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builder.rb:116:in `call'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `block in run'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in `busy'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `run'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/machine.rb:147:in `action'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/provision/command.rb:26:in `block in execute'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/plugin/v2/command.rb:182:in `block in with_target_vms'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/plugin/v2/command.rb:180:in `each'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/plugin/v2/command.rb:180:in `with_target_vms'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/provision/command.rb:25:in `execute'

            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/cli.rb:46:in `execute'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/environment.rb:467:in `cli'
            from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.2.2/bin/vagrant:84:in `<top (required)>'
            from C:/Program Files (x86)/HashiCorp/Vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23:in `load'
            from C:/Program Files (x86)/HashiCorp/Vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23:in `<main>'
```

I've been using the following workaround: 

```
require 'rbconfig'
is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)
config.vm.synced_folder "puppet/modules", "/ProgramData/PuppetLabs/puppet/etc/modules" if is_windows

config.vm.provision :puppet, :options => ["--verbose --environment vagrant"] do |puppet|
  puppet.module_path    = "puppet/modules" if not is_windows
  puppet.manifests_path = "puppet/manifests"
  puppet.manifest_file  = "default.pp"
  puppet.facter = {
    "domain" => "local",
    "kernel" => "windows",
    "operatingsystem" => "windows",
    "osfamily" => "windows"
  }
end
```

**Comment by sneal** [comment]
Do you get the same error on the Windows host with a newer version of Vagrant? IIRC that error happens on older versions of Vagrant instead of properly reporting back the real config validation error.

Its likely a pathing problem on Windows hosts, but its hard to tell given the error and I don't have a Windows host handy to try and reproduce it.

**Comment by tvjames** [comment]
I'm running vagrant 1.2.2 so I'll upgrade and get back to you.

**Comment by ferventcoder** [comment]
1.2.2 was one that definitely had issues with vagrant windows.

On Monday, September 30, 2013, Thomas James wrote:

> I'm running vagrant 1.2.2 so I'll upgrade and get back to you.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WinRb/vagrant-windows/issues/107#issuecomment-25420077
> .

## 

---

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by tvjames** [comment]
Yup, that was the issue, upgraded to 1.3.3 and the issue is no more. Thanks.
