### ISSUE TITLE
Vagrant-windows install failure on CentOS 6.4

### ISSUE THREAD

**Issue by tendervittles** [WinRb/vagrant-windows#123]
Hello,

Vagrant plugin install vagrant-windows failed on CentOS 6.4.

Please let me know if this should be filed as a Vagrant issue.

It appears that vagrant-windows is including /opt/vagrant/embedded/include/zlib.h during the compile. However, it is linking against my system's zlib, which doesn't have the exact same symbols. This breaks the install.

As a fast workaround I moved Vagrant's zlib.h to zlib.h.orig. This forces vagrant-windows to build against my system's header and library, so all symbols match.

My host details:

``` text
# cat /etc/redhat-release
CentOS release 6.4 (Final)
# uname -a
Linux server1 2.6.32-358.14.1.el6.x86_64 #1 SMP Tue Jul 16 23:51:20 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
# vagrant --version
Vagrant 1.3.4
```

When I try to install vagrant-windows I get this error below:

``` text
/opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:562:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

        /opt/vagrant/embedded/bin/ruby extconf.rb
Extracting libxml2-2.8.0.tar.gz into tmp/x86_64-redhat-linux/ports/libxml2/2.8.0... OK
Running 'configure' for libxml2 2.8.0... OK
Running 'compile' for libxml2 2.8.0... ERROR, review 'tmp/x86_64-redhat-linux/ports/libxml2/2.8.0/compile.log' to see what happened.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.
```

The compile.log shows an undefined reference to gzopen64. My system's zlib library doesn't have this symbol.

``` text
  CCLD   xmllint
./.libs/libxml2.so: undefined reference to `gzopen64'
collect2: ld returned 1 exit status
make[2]: *** [xmllint] Error 1
make[2]: Leaving directory `/me/.vagrant.d/gems/gems/nokogiri-1.6.0/ext/nokogiri/tmp/x86_64-redhat-linux/ports/libxml2/2.8.0/libxml2-2.8.0'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/me/.vagrant.d/gems/gems/nokogiri-1.6.0/ext/nokogiri/tmp/x86_64-redhat-linux/ports/libxml2/2.8.0/libxml2-2.8.0'
make: *** [all] Error 2
```

Thanks!

**Comment by tendervittles** [comment]
The problem isn't with vagrant-windows. It is with Vagrant's x86_64 rpm. The file .vagrant.d/gems/gems/nokogiri-1.6.0/ext/nokogiri/tmp/x86_64-redhat-linux/ports/libxml2/2.8.0/libxml2-2.8.0/config.log is littered with:

``` text
configure:3388: gcc -I/opt/vagrant/bin/../embedded/include -L/opt/vagrant/bin/../embedded/lib}  -I/opt/vagrant/bin/../embedded/include -L/opt/vagrant/bin/../embedded/lib} conftest.c  >&5
```

See how the -L ends with }. This is causing the problem.

It appears that /opt/vagrant/bin/vagrant is the culprit. These lines should not end with }.

``` bash
# Append our include/lib search path to the flags and make sure they're
# exported so that any child processes have access to them.
export CFLAGS="${CFLAGS}-I${EMBEDDED_DIR}/include -L${EMBEDDED_DIR}/lib}"
export LDFLAGS="${LDFLAGS}-I${EMBEDDED_DIR}/include -L${EMBEDDED_DIR}/lib}"
```

**Comment by sneal** [comment]
Nice work figuring this out!

**Comment by josepedrocorreia** [comment]
Hi everyone,

I am having a very similar problem which, however, does not go away after fixing `/opt/vagrant/bin/vagrant` as indicated above. Here's what I get after running `vagrant plugin install vagrant-windows`:

```
Installing the 'vagrant-windows' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:562:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

        /opt/vagrant/embedded/bin/ruby extconf.rb
Extracting libxml2-2.8.0.tar.gz into tmp/i686-redhat-linux/ports/libxml2/2.8.0... OK
Running 'configure' for libxml2 2.8.0... ERROR, review 'tmp/i686-redhat-linux/ports/libxml2/2.8.0/configure.log' to see what happened.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/opt/vagrant/embedded/bin/ruby
/home/correia/.vagrant.d/gems/gems/mini_portile-0.5.2/lib/mini_portile.rb:265:in `block in execute': Failed to complete configure task (RuntimeError)
    from /home/correia/.vagrant.d/gems/gems/mini_portile-0.5.2/lib/mini_portile.rb:257:in `chdir'
    from /home/correia/.vagrant.d/gems/gems/mini_portile-0.5.2/lib/mini_portile.rb:257:in `execute'
    from /home/correia/.vagrant.d/gems/gems/mini_portile-0.5.2/lib/mini_portile.rb:65:in `configure'
    from /home/correia/.vagrant.d/gems/gems/mini_portile-0.5.2/lib/mini_portile.rb:108:in `cook'
    from extconf.rb:101:in `block in <main>'
    from extconf.rb:119:in `call'
    from extconf.rb:119:in `block in <main>'
    from extconf.rb:109:in `tap'
    from extconf.rb:109:in `<main>'


Gem files will remain installed in /home/correia/.vagrant.d/gems/gems/nokogiri-1.6.0 for inspection.
Results logged to /home/correia/.vagrant.d/gems/gems/nokogiri-1.6.0/ext/nokogiri/gem_make.out
    from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:540:in `block in build_extensions'
    from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:515:in `each'
    from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:515:in `build_extensions'
    from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/installer.rb:180:in `install'
    from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/dependency_installer.rb:297:in `block in install'
    from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/dependency_installer.rb:270:in `each'
    from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/dependency_installer.rb:270:in `each_with_index'
    from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/dependency_installer.rb:270:in `install'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/plugins/commands/plugin/action/install_gem.rb:49:in `block in call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/plugins/commands/plugin/gem_helper.rb:42:in `block in with_environment'
    from /opt/vagrant/embedded/lib/ruby/1.9.1/rubygems/user_interaction.rb:40:in `use_ui'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/plugins/commands/plugin/gem_helper.rb:41:in `with_environment'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/plugins/commands/plugin/action/install_gem.rb:39:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/plugins/commands/plugin/action/bundler_check.rb:20:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/lib/vagrant/action/runner.rb:61:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/lib/vagrant/action/runner.rb:61:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/plugins/commands/plugin/command/base.rb:17:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/plugins/commands/plugin/command/install.rb:44:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/plugins/commands/plugin/command/root.rb:47:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/lib/vagrant/cli.rb:46:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/lib/vagrant/environment.rb:478:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.7/bin/vagrant:84:in `<top (required)>'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
```

Notice that `libxml2 2.8.0` fails to `configure`, rather than `compile`. I am running VirtualBox 4.2 and Vagrant 1.2.7 on Scientific Linux 6.4.

**Comment by josepedrocorreia** [comment]
BTW, the log at `~/.vagrant.d/gems/gems/nokogiri-1.6.0/ext/nokogiri/tmp/i686-redhat-linux/ports/libxml2/2.8.0/configure.log` says `error: cannot find sources (entities.c)`

**Comment by czablocki** [comment]
I'm having a similar issue with vagrant 1.3.5 64-bit binaries on Ubuntu 12.04

This is also after manually updating /opt/vagrant/bin/vagrant to remove the extra '}' characters

The build fails when trying to compile libxslt2

Not sure if this is a problem with vagrant-windows, vagrant, nokogiri, or what, but it's really frustrating

**Comment by juliandunn** [comment]
I think you need the libxslt and libxml2 devel RPMs in order to compile.

**Comment by sneal** [comment]
Eventually I'll document the steps needed to install vagrant-windows on Ubuntu 12.04 - since I need to replace our Mac build agent, but at my current rate Ubuntu 14.04 might be out first. Any help documenting this would be heartily welcomed.
