### ISSUE TITLE
`vagrant plugin install vagrant-windows` fails

### ISSUE THREAD

**Issue by steenhulthin** [WinRb/vagrant-windows#140]
I put this issue on [stackoverflow](http://stackoverflow.com/questions/20146758/vagrant-plugin-install-vagrant-windows-fails). Should have put it here first. sry.

---

I'm trying to install the vagrant-windows plugin on a windows 7 (64 bit) machine, but I get the error below. How can I fix this?

further info:
- ruby version installed on machine 1.9.3
- in corporate environment (port 80, 443, 3389 open)
- Vagrant installed via chocolatey (version 1.3.5)

This is the stacktrace:

```
Installing the 'vagrant-windows' plugin. This can take a few minutes...
C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems.rb:566:in `inflate': incorrect header check (Zlib::DataError)
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems.rb:566:in `inflate'
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/spec_fetcher.rb:122:in `fetch_spec'
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/spec_fetcher.rb:95:in `block in fetch_with_errors'
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/spec_fetcher.rb:94:in `map'
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/spec_fetcher.rb:94:in `fetch_with_errors'
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:110:in `find_gems_with_sources'
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:174:in `block in add_found_dependencies'
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:171:in `each'
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:171:in `add_found_dependencies'
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:142:in `gather_dependencies'
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:267:in `install'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/commands/plugin/action/install_gem.rb:49:in `block in call'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/commands/plugin/gem_helper.rb:42:in `block in with_environment'
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/user_interaction.rb:40:in `use_ui'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/commands/plugin/gem_helper.rb:41:in `with_environment'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/commands/plugin/action/install_gem.rb:39:in `call'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/commands/plugin/action/bundler_check.rb:20:in `call'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builder.rb:116:in `call'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/commands/plugin/command/base.rb:17:in `action'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/commands/plugin/command/install.rb:27:in `execute'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/commands/plugin/command/root.rb:52:in `execute'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/cli.rb:38:in `execute'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/environment.rb:478:in `cli'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/bin/vagrant:96:in `<top (required)>'
    from C:/HashiCorp/Vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23:in `load'
    from C:/HashiCorp/Vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23:in `<main>'
```

**Comment by sneal** [comment]
It almost seems like a corrupted download. Are you able to install other plugins? You may want to try another host or reinstall Vagrant.

**Comment by steenhulthin** [comment]
I did install the vagrant-vbox-snapshot without errors. 

I also tried uninstalling and installing vagrant again. 

I did not have any problems on my windows 8.1 host machine. This machine is however not in a corporate environment.

**Comment by steenhulthin** [comment]
Hm, There is something weird going on. It seems to be a machine environment specific problem. I disabled all unused network adaptor and now the the plugin installed. 

I'm closing the issue since this is most likely not a general problem.
