### ISSUE TITLE
Plugin fails to load with Vagrant 1.4

### ISSUE THREAD

**Issue by sneal** [WinRb/vagrant-windows#150]
Forgot to run bundle exec from within my development directory. Loads fine.

**Comment by reidmv** [comment]
Just installed Vagrant 1.4 and uninstalled/reinstalled vagrant-windows (1.3.2) plugin. Not using a development environment, just installing. Plugin fails to load for me. I get this output with --debug:

```
 INFO environment: Loading plugin from JSON: vagrant-windows
ERROR root: Failed to load plugin: vagrant-windows
ERROR root:  -- Error: #<LoadError: cannot load such file -- /Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/providers/virtual
box/action/share_folders>
ERROR root:  -- Backtrace:
ERROR root: /Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
/Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
/Users/reidmv/.vagrant.d/gems/gems/vagrant-windows-1.3.2/lib/vagrant-windows/monkey_patches/plugins/providers/virtualbox/action/share_folders
.rb:1:in `<top (required)>'
/Users/reidmv/.vagrant.d/gems/gems/vagrant-windows-1.3.2/lib/vagrant-windows/plugin.rb:15:in `require_relative'
/Users/reidmv/.vagrant.d/gems/gems/vagrant-windows-1.3.2/lib/vagrant-windows/plugin.rb:15:in `<top (required)>'
/Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
/Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
/Users/reidmv/.vagrant.d/gems/gems/vagrant-windows-1.3.2/lib/vagrant-windows.rb:24:in `<top (required)>'
/Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:118:in `require'
/Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:118:in `rescue in require'
/Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:124:in `require'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant.rb:197:in `require_plugin'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/environment.rb:760:in `block in load_plugins'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/environment.rb:751:in `each'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/environment.rb:751:in `load_plugins'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/environment.rb:132:in `initialize'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/bin/vagrant:105:in `new'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/bin/vagrant:105:in `<top (required)>'
/Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
/Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
 INFO interface: error: Failed to load the "vagrant-windows" plugin. View logs for more details.

Failed to load the "vagrant-windows" plugin. View logs for more details.
```

Not sure what's wrong but it's definitely not plug-n-play for me right now.

**Comment by sneal** [comment]
See issue #151. I closed this prematurely.
