### ISSUE TITLE
Configurating network adapter failed when NON-ASCII adapter name used.

### ISSUE THREAD

**Issue by toruuetani** [WinRb/vagrant-windows#182]
- Vagrant: 1.5.1
- Vagrant-Windows: 1.6.0
- Host: Windows 8.1 Pro(x64)
- Guest: Windows 7 SP1 Pro(x86 | x64) 

When I execute `vagrant up`, configurating network adapter failed.
In my guest, adapter name are `ローカル エリア接続`, `ローカル エリア接続 2`, `ローカル エリア接続 3`. (NOTE: this is Japanese)
My `vagrantfile` is below.

``` rb
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.guest = :windows
  config.vm.box = "win7x64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end

  config.vm.network :forwarded_port, guest: 3389, host: 13389
  config.vm.network :forwarded_port, guest: 5985, host: 15985, id: "winrm", auto_correct: true

  config.vm.network "private_network", ip: "192.168.56.101", :netmask => "255.255.255.0"
  config.vm.network "public_network", ip: "192.168.2.1", :netmask => "255.255.255.0"
end
```

At first, `vagrant up` failed by error. Error log is below.

```
Shell: powershell
Command: netsh interface ip set address "ローカル エリア接続 2" static 192.168.56.101
255.255.255.0
Message: U+30ED from UTF-8 to ASCII-8BIT
 INFO interface: Machine: error-exit ["VagrantWindows::Errors::WinRMExecutionError",
"An error occurred executing a remote WinRM command.\n\nShell: powershell\nCommand: n
etsh interface ip set address \"\u30ED\u30FC\u30AB\u30EB \u30A8\u30EA\u30A2\u63A5\u7D
9A 2\" static 192.168.56.101 255.255.255.0\nMessage: U+30ED from UTF-8 to ASCII-8BIT"
]
```

This error is raised at line 259 in `winrm/winrm_service.rb`.
So I modify code like this => `script = script.force_encoding('ASCII-8BIT')`
This modification works fine, `vagrant up` succeeded. But network adapters have invalid IP addresses.

On the other hand, no modifying code and modifying network adapter name to ASCII-NAME in guest works fine. Network adapters have valid IP addresses.

Any suggestions?

**Comment by sneal** [comment]
When you run the ASCII-8BIT encoded command directly on the guest does it succeed? i.e.

`netsh interface ip set address \"\xE3\x83\xAD\xE3\x83\xBC\xE3\x82\xAB\xE3\x83\xAB \xE3\x82\xA8\xE3\x83\xAA\xE3\x82\xA2\xE6\x8E\xA5\xE7\xB6\x9A 2\" static 192.168.56.101`

**Comment by toruuetani** [comment]
Thanks for your reply.

I tried below command on the guest. The ASCII-8BIT encoded command does not succeed.
So I think that powershell needs "UTF-16LE" encoded command.

```
@cmd
netsh interface ip set address \"\xE3\x83\xAD\xE3\x83\xBC\xE3\x82\xAB\xE3\x83\xAB \xE3\x82\xA8\xE3\x83\xAA\xE3\x82\xA2\xE6\x8E\xA5\xE7\xB6\x9A 2\" static 192.168.56.101 255.255.255.0
=> failed by "file name, directory name, or volume label syntax is incorrect."


@irb
s = "netsh interface ip set address \"ローカル エリア接続 2\" static 192.168.56.101 255.255.255.0"
s.encoding
=> #<Encoding:Windows-31J>
s << "\00"
Base64.strict_encode64(s)
=> "bmV0c2ggaW50ZXJmYWNlIGlwIHNldCBhZGRyZXNzICKDjYFbg0qDiyCDR4OKg0GQ2pGxIDIiIHN0YXRpYyAxOTIuMTY4LjU2LjEwMSAyNTUuMjU1LjI1NS4wAA=="

@cmd
> powershell -Command "netsh interface ip set address \"ローカル エリア接続 2\" static 192.168.56.101 255.255.255.0"
=> succeeded
> powershell -EncodedCommand "bmV0c2ggaW50ZXJmYWNlIGlwIHNldCBhZGRyZXNzICKDjYFbg0qDiyCDR4OKg0GQ2pGxIDIiIHN0YXRpYyAxOTIuMTY4LjU2LjEwMSAyNTUuMjU1LjI1NS4wAA=="
=> failed by not recognized name


@irb
us = s.encode("UTF-8")
=> "netsh interface ip set address \"\u30ED\u30FC\u30AB\u30EB \u30A8\u30EA\u30A2\u63A5\u7D9A 2\" static 192.168.56.101 255.255.255.0\u0000"
Base64.strict_encode64(us)
=> "bmV0c2ggaW50ZXJmYWNlIGlwIHNldCBhZGRyZXNzICLjg63jg7zjgqvjg6sg44Ko44Oq44Ki5o6l57aaIDIiIHN0YXRpYyAxOTIuMTY4LjU2LjEwMSAyNTUuMjU1LjI1NS4wAA=="

@cmd
> powershell -EncodedCommand "bmV0c2ggaW50ZXJmYWNlIGlwIHNldCBhZGRyZXNzICLjg63jg7zjgqvjg6sg44Ko44Oq44Ki5o6l57aaIDIiIHN0YXRpYyAxOTIuMTY4LjU2LjEwMSAyNTUuMjU1LjI1NS4wAA=="
=> failed by not recognized name


@irb
u16s = us.encode("UTF-16LE")
=> "netsh interface ip set address \"\u30ED\u30FC\u30AB\u30EB \u30A8\u30EA\u30A2\u63A5\u7D9A 2\" static 192.168.56.101 255.255.255.0\u0000"
Base64.strict_encode64(u16s)
=> "bgBlAHQAcwBoACAAaQBuAHQAZQByAGYAYQBjAGUAIABpAHAAIABzAGUAdAAgAGEAZABkAHIAZQBzAHMAIAAiAO0w/DCrMOswIACoMOowojClY5p9IAAyACIAIABzAHQAYQB0AGkAYwAgADEAOQAyAC4AMQA2ADgALgA1ADYALgAxADAAMQAgADIANQA1AC4AMgA1ADUALgAyADUANQAuADAAAAA="

@cmd
> powershell -EncodedCommand "bgBlAHQAcwBoACAAaQBuAHQAZQByAGYAYQBjAGUAIABpAHAAIABzAGUAdAAgAGEAZABkAHIAZQBzAHMAIAAiAO0w/DCrMOswIACoMOowojClY5p9IAAyACIAIABzAHQAYQB0AGkAYwAgADEAOQAyAC4AMQA2ADgALgA1ADYALgAxADAAMQAgADIANQA1AC4AMgA1ADUALgAyADUANQAuADAAAAA="
=> succeeded


@irb
as = s.dup
as.force_encoding("ASCII-8BIT")
=> "netsh interface ip set address \"\x83\x8D\x81[\x83J\x83\x8B \x83G\x83\x8A\x83A\x90\xDA\x91\xB1 2\" static 192.168.56.101 255.255.255.0\x00"

@cmd
> powershell -Command "netsh interface ip set address \"\x83\x8D\x81[\x83J\x83\x8B \x83G\x83\x8A\x83A\x90\xDA\x91\xB1 2\" static 192.168.56.101 255.255.255.0\x00"
=> failed by "file name, directory name, or volume label syntax is incorrect."


@irb
aus = us.dup
aus.force_encoding("ASCII-8BIT")
=> "netsh interface ip set address \"\xE3\x83\xAD\xE3\x83\xBC\xE3\x82\xAB\xE3\x83\xAB \xE3\x82\xA8\xE3\x83\xAA\xE3\x82\xA2\xE6\x8E\xA5\xE7\xB6\x9A 2\" static 192.168.56.101 255.255.255.0\x00"

@cmd
powershell -Command "netsh interface ip set address \"\xE3\x83\xAD\xE3\x83\xBC\xE3\x82\xAB\xE3\x83\xAB \xE3\x82\xA8\xE3\x83\xAA\xE3\x82\xA2\xE6\x8E\xA5\xE7\xB6\x9A 2\" static 192.168.56.101 255.255.255.0\x00"
=> failed by "file name, directory name, or volume label syntax is incorrect."


@irb
Base64.strict_encode64(aus)
=> "bmV0c2ggaW50ZXJmYWNlIGlwIHNldCBhZGRyZXNzICLjg63jg7zjgqvjg6sg44Ko44Oq44Ki5o6l57aaIDIiIHN0YXRpYyAxOTIuMTY4LjU2LjEwMSAyNTUuMjU1LjI1NS4wAA=="

@cmd
powershell -EncodedCommand "bmV0c2ggaW50ZXJmYWNlIGlwIHNldCBhZGRyZXNzICLjg63jg7zjgqvjg6sg44Ko44Oq44Ki5o6l57aaIDIiIHN0YXRpYyAxOTIuMTY4LjU2LjEwMSAyNTUuMjU1LjI1NS4wAA=="
=> failed by not recognized name


@irb
au16s = u16s.dup
au16s.force_encoding("ASCII-8BIT")
=> "n\x00e\x00t\x00s\x00h\x00 \x00i\x00n\x00t\x00e\x00r\x00f\x00a\x00c\x00e\x00\x00i\x00p\x00 \x00s\x00e\x00t\x00 \x00a\x00d\x00d\x00r\x00e\x00s\x00s\x00 \x00\"\x00\xED0\xFC0\xAB0\xEB0 \x00\xA80\xEA0\xA20\xA5c\x9A} \x002\x00\"\x00 \x00s\x00t\x00a\x00t\x00i\x00c\x00 \x001\x009\x002\x00.\x001\x006\x008\x00.\x005\x006\x00.\x001\x000\x001\x00 \x002\x005\x005\x00.\x002\x005\x005\x00.\x002\x005\x005\x00.\x000\x00\x00\x00"

@cmd
powershell -Command "n\x00e\x00t\x00s\x00h\x00 \x00i\x00n\x00t\x00e\x00r\x00f\x00a\x00c\x00e\x00\x00i\x00p\x00 \x00s\x00e\x00t\x00 \x00a\x00d\x00d\x00r\x00e\x00s\x00s\x00 \x00\"\x00\xED0\xFC0\xAB0\xEB0 \x00\xA80\xEA0\xA20\xA5c\x9A} \x002\x00\"\x00 \x00s\x00t\x00a\x00t\x00i\x00c\x00 \x001\x009\x002\x00.\x001\x006\x008\x00.\x005\x006\x00.\x001\x000\x001\x00 \x002\x005\x005\x00.\x002\x005\x005\x00.\x002\x005\x005\x00.\x000\x00\x00\x00"
=> failed by not recognized name
```

**Comment by sneal** [comment]
Could you send a pull request for this?

**Comment by toruuetani** [comment]
I tried to fix this issue before reporting, but i could not fix it.
I think I need to modify "WinRM.WinRMService.run_powershell_script".

I modified code like below.

```
#line 259 script = script.encode('ASCII-8BIT')
script = script.encode('UTF-16LE')
```

but VM was shutdowned.

```
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
C:/Users/username/.vagrant.d/gems/gems/vagrant-windows-1.6.0/lib/vagrant-windows/communication
/guestnetwork.rb:94:in `Integer': invalid value for Integer(): "" (ArgumentError)
        from C:/Users/username/.vagrant.d/gems/gems/vagrant-windows-1.6.0/lib/vagrant-windows/
communication/guestnetwork.rb:94:in `wsman_version'
```

I will try to modify a little more.

**Comment by sneal** [comment]
Any luck with this?

**Comment by toruuetani** [comment]
Sorry, I couldn't yet.

**Comment by PandaDrunkard** [comment]
Seen the same problem, and I did same approach above. That muted the error and up VM successfully, but the actual IP of Local Network 2 didn't change.

Vagrant 1.4.3 on Cygwin with Windows 7 x64

**Comment by toruuetani** [comment]
I sent PR(https://github.com/WinRb/WinRM/pull/70) to fix this.
But I don't know how to test this plugin, please test !

**Comment by sneal** [comment]
@toruuetani Nice! I'll see if I can't this shepherded into WinRM and Vagrant core (since 1.6+ supports Windows guests).

**Comment by PandaDrunkard** [comment]
:+1:  It works fine with my Vagrant as well :)

**Comment by toruuetani** [comment]
@PandaDrunkard Thank you for your testing!

**Comment by ccariou** [comment]
@toruuetani , how did you resolve the second error : "...Integer': invalid value for Integer(): "" (ArgumentError)..." ?

**Comment by lonniev** [comment]
@sneal Haven't figured out why this is happening but with an older Windows XP Pro SP3 base box, the name of the adapter that is set as NAT in VirtualBox can appear in the `netsh ip set address "name" dhcp` command sent over WinRM as "". That is, it is a quoted nil value.

The result is that netsh pukes.

A similar Vagrant and Virtualbox configuration for a modern.ie Windows 7 base box properly configures the network adapter fine.

**Comment by sneal** [comment]
This plugin is no longer maintained since Vagrant natively supports Windows guests. If you have a Vagrant issue you need to ask the Vagrant mailing list or file a GitHub issue on [Vagrant core](https://github.com/mitchellh/vagrant).

BTW - Windows XP is unsupported.

**Comment by lonniev** [comment]
np. I was just passing along an observation. I'm not using the plugin form of the WinRM support and no longer the old XP image.

**Comment by plcosta** [comment]
I seen the same problem in windows 7 64 bits and vagrant 1.7.2. I solved it changing network name to one word. It works fine!
