### ISSUE TITLE
synced_folder does not work with Windows

### ISSUE THREAD

**Issue by KAllan357** [WinRb/vagrant-windows#30]
Using Vagrant 1.1.5 and vagrant-windows 1.0.0.

I'm getting the following error from Vagrant:

```
ERROR vagrant: /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/config_validate.rb:18:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:51:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:51:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builder.rb:109:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/machine.rb:129:in `action'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/destroy/command.rb:23:in `block in execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:182:in `block in with_target_vms'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:180:in `each'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:180:in `with_target_vms'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/destroy/command.rb:22:in `execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/cli.rb:46:in `execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/environment.rb:408:in `cli'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/bin/vagrant:75:in `<top (required)>'
/Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
/Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
 INFO interface: error: There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The shared folder guest path must be absolute: C:/mounted-packages
```

The relevant part of my Vagrantfile is:

```
artifacts_dir = "C:/mounted-packages"
config.vm.synced_folder build_output_dir, artifacts_dir
```

Is it possible this was fixed in a newer version of Vagrant, but is unreachable because of the backwards incompatibility with vagrant-windows 1.0.0? Or am I just doing something wrong here?

**Comment by KAllan357** [comment]
After doing some digging, it seems like this is actually a bug in vagrant.

https://github.com/mitchellh/vagrant/issues/1688

**Comment by pmorton** [comment]
Cool. I will leave this open for the moment. I want to see where it goes.

**Comment by pmorton** [comment]
@KAllan357 I was thinking about this a bit and vagrant-windows does not support synced folders. It *could support synced folders but is has not yet been implemented in the guest driver.

**Comment by KAllan357** [comment]
Does the Vagrant 1.1 `synced_folder` syntax imply something completely different from the 1.0 `share_folder` style? Perhaps I just missed something on the documentation side of how to share a folder with my VM.

**Comment by sneal** [comment]
Closing this issue, this works correctly on vagrant 1.2.2 and vagrant-windows 1.2 branch.

`config.vm.synced_folder "/Users/sneal/src", "/src"`

Creates a synced folder on the guest accessible via c:\src
